version: '3'

services:
  mqtt-subscriber:
    image: mqtt-subscriber
    build: ./mqtt/sensor_subscriber
    restart: always
    ports:
      - "8888:5000"
    depends_on:
      - influxdb
    networks:
      - influx-subscriber-network

  influxdb:
    image: influxdb:1.8
    restart: always
    ports:
      - 8086:8086
    networks:
      - influx-subscriber-network
    volumes:
      - ./influxdb/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - influxdb:/var/lib/influxdb

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./system_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./system_db/populate_database.sql:/docker-entrypoint-initdb.d/populate_database.sql
    networks:
      - mysql-gui
    environment:
      MYSQL_DATABASE: HealthSystemDB

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-gui

networks:
  influx-subscriber-network:
  mysql-gui:

volumes:
  influxdb:
