version: '3'

services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-user-secret
      MYSQL_USER_FILE: /run/secrets/mysql-user-secret
      MYSQL_PASSWORD_FILE: /run/secrets/mysql-user-password
    secrets:
      - mysql-root-user-secret
      - mysql-user-secret
      - mysql-user-password

secrets:
  mysql-root-user-secret:
    file: ./secrets/mysql-root-password.txt
  mysql-user-secret:
    file: ./secrets/mysql-user-secret.txt
  mysql-user-password:
    file: ./secrets/mysql-user-password.txt

